module.exports = {
  apps: [
    {
      name: 'yukiko-discord',
      script: './node_modules/.bin/tsx',
      args: '--env-file=.env platforms/discord/src/index.ts',
      cwd: 'your-home-path/yukiko',
      watch: false,
      env: { NODE_ENV: 'production', PLATFORM: 'discord' },
      error_file: './logs/discord-error.log',
      out_file: './logs/discord-out.log',
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: 'yukiko-telegram',
      script: './node_modules/.bin/tsx',
      args: '--env-file=.env platforms/telegram/src/index.ts',
      cwd: 'your-home-path/yukiko',
      watch: false,
      env: { NODE_ENV: 'production', PLATFORM: 'telegram' },
      error_file: './logs/telegram-error.log',
      out_file: './logs/telegram-out.log',
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: 'yukiko-agent',
      script: './node_modules/.bin/tsx',
      args: '--env-file=.env homelab-agent/agent.ts',
      cwd: 'your-home-path/yukiko',
      watch: false,
      env: { NODE_ENV: 'production' },
      error_file: './logs/agent-error.log',
      out_file: './logs/agent-out.log',
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: 'yukiko-mobile',
      script: './node_modules/.bin/tsx',
      args: '--env-file=.env platforms/mobile/src/index.ts',
      cwd: 'your-home-path/yukiko',
      watch: false,
      env: { NODE_ENV: 'production', PLATFORM: 'mobile' },
      error_file: './logs/mobile-error.log',
      out_file: './logs/mobile-out.log',
      restart_delay: 5000,
      max_restarts: 10,
    },
  ],
};
